# Generated by Django 5.2.1 on 2025-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_score_level_alter_score_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiskilling',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
