# Generated by Django 5.1 on 2025-07-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_multiskilling_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(default='HRM-F-26', max_length=20)),
                ('rev_no', models.CharField(default='00', max_length=10)),
                ('rev_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='STLDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('rev_no', models.CharField(max_length=10)),
                ('rev_date', models.DateField()),
                ('rev_history', models.TextField()),
                ('reason_for_change', models.TextField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_logs', to='app1.intakesheet')),
            ],
            options={
                'ordering': ['sno'],
            },
        ),
        migrations.CreateModel(
            name='SheetHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_signature', models.ImageField(blank=True, null=True, upload_to='signatures/admin/')),
                ('dojo_person_name', models.CharField(max_length=100)),
                ('dojo_signature', models.ImageField(blank=True, null=True, upload_to='signatures/dojo/')),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='app1.intakesheet')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('temp_id', models.CharField(editable=False, help_text='Auto-generated temporary ID for the candidate', max_length=50, unique=True)),
                ('contractor_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Casual', 'Casual'), ('NAPS', 'NAPS')], max_length=20)),
                ('candidate_name', models.CharField(max_length=100)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('bio_data_submitted', models.FileField(blank=True, null=True, upload_to='biodata/')),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('intake', 'Intake Complete'), ('training', 'In Training'), ('evaluation', 'In Evaluation'), ('passed', 'Passed'), ('failed', 'Failed'), ('deployed', 'Deployed')], default='intake', help_text='Current status in the STL workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app1.intakesheet')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stldepartment')),
            ],
            options={
                'ordering': ['sr_no'],
                'unique_together': {('sheet', 'sr_no')},
            },
        ),
    ]
